name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.5"

      - name: Get version from tag
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Build binary
        run: make release

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ env.VERSION }}"
          tag_name: "${{ env.VERSION }}"
          files: vis
